📚 Publish pro on but registry
okp4/okp4d pull request #183
Opened 2022-10-11 13:37 UTC by bdeneux

Publish protobuf file on buf registry.

The lint process before the publish is already done on [lint workflow](https://github.com/okp4/okp4d/blob/main/.github/workflows/lint.yml#L121). 

#### ✏️ Todo
Before merge, this step is **mandatory** and can only be done by account holder.
- [ ] Create buf account 
- [ ] Register okp4 and okp4d repository : `buf beta registry repository create buf.build/okp4/okp4d --visibility public`
- [ ] Register `BUF_TOKEN` into GitHub action environment variables.

2023-01-10 16:24 UTC, ccamel commented
@bdeneux A must have. 😃 The required actions are underway...

2023-01-10 17:07 UTC, hleonardtek approved these changes

2023-01-13 15:12 UTC, bdeneux commented
@ccamel @amimart @hleonardtek @ad2ien Buf accoutn has been created, `BUF_TOKEN` has been added to the organisation secret ans but repository has been created (thanks @jeremylgn), this PR is ready to be reviewed 😇.

2023-01-13 15:57 UTC, ccamel requested changes
minor comment ;)

2023-01-13 15:57 UTC, ccamel commented on .github/workflows/build.yml
> +    runs-on: ubuntu-20.04
You can use the version `ubuntu-22.04` in order to be aligned with the other runners versions.

```suggestion
    runs-on: ubuntu-22.04
```

2023-01-13 16:23 UTC, ccamel approved these changes
Great! Thanks :+1:

2023-01-14 12:11 UTC, hleonardtek approved these changes
:+1:

2023-01-16 09:50 UTC, amimart approved these changes
Great 🙏

2023-01-16 09:51 UTC, merged

2023-01-16 10:40 UTC, jeremylgn reviewed
:+1: