Bump: ledger v0.9.3
okp4/okp4d pull request #185
Opened 2022-10-11 22:03 UTC by Galadrin

- Upgrade Ledger module to v0.9.3 to support latest Ledger model.
- Enable ledger support in binary.

Signed-off-by: dpierret <dapie@cros-nest.com>

2022-10-12 08:25 UTC, bdeneux commented
Thanks for contributing @Galadrin ! ☺️. 

Adding ledger support require to add `linux-headers` package dependency on the docker container to make it working. 
https://github.com/okp4/okp4d/blob/main/Dockerfile#L12
```Dockerfile
...
# hadolint ignore=DL4006
RUN set -eux \
    && apk add --no-cache ca-certificates=20220614-r0 build-base=0.5-r3 git=2.36.2-r0 linux-headers=5.16.7-r1 \
...
```

We could also follow `cosmos-sdk` to integrate ledger support depending on the platform : https://github.com/cosmos/cosmos-sdk/blob/main/Makefile#L24-L45.

2022-10-12 08:35 UTC, Galadrin commented
Yes, I have the docker build running to check

2022-10-12 08:37 UTC, ccamel commented
@Galadrin thanks for the cotribution. I've activated the CI on your PR so that you can follow the workflow.

2022-10-13 08:46 UTC, amimart requested changes
Thank you for bringing this, it looks almost good to me, just a little remark to make the linter happy.

2022-10-13 08:46 UTC, amimart commented on Dockerfile
> +    linux-headers
`ca-certificates` and `build-base` packages are already installed lower, I propose to add `linux-headers` with them and remove this `RUN` instruction.

Regarding the `linux-headers` package please reference its version (i.e. `linux-headers=5.16.7-r1`), the linter will appreciate 😉

2022-10-13 09:09 UTC, amimart approved these changes
Seems good to me thank you!

2022-10-13 09:36 UTC, ccamel approved these changes

2022-10-13 09:48 UTC, merged