🧠 Logic: 🗂️ source_file/1 predicate
okp4/okp4d pull request #311
Opened 2023-03-16 10:20 UTC by amimart

Implements #308 

Refer to the issue concerning the predicate definition.

Regarding the implementation, to manage only files loaded as prolog sources a trick has been done using reflection on the prolog VM.

2023-03-16 13:12 UTC, amimart commented on x/logic/predicate/file.go
> +	)
You're totally right!

2023-03-16 15:28 UTC, bdeneux approved these changes
Very nice 😁 That seems good to me 👍

2023-03-17 12:24 UTC, ccamel requested changes

2023-03-17 12:24 UTC, ccamel commented on x/logic/predicate/file_test.go
> +			},
If the returned sources are sorted, add a test case which shows it. For example:
```go
          {
				query:       "consult(file2), consult(file3), consult(file1), source_file(X).",
				wantResult:  []types.TermResults{{"X": "file1"}, {"X": "file2"}, {"X": "file3"}},
				wantSuccess: true,
			},
```

2023-03-17 12:24 UTC, ccamel commented on x/logic/predicate/file.go
> +		loaded[value.String()] = nil
I usually use a `map[string]struct{}` to represent sets, with `struct{}{}` as an `empty` value (unique and named). But this is a matter of taste.

2023-03-17 13:05 UTC, ccamel approved these changes
All good. Great improvement.

2023-03-17 13:06 UTC, merged