🧠 Logic: ⛓️ Implement `read_string/3` predicate
okp4/okp4d pull request #381
Opened 2023-06-14 21:12 UTC by bdeneux

2023-06-19 15:03 UTC, amimart requested changes
The implementation looks good to me :)

I just pointed out some grammatical mistakes in error messages, I've suggested some correction rephrasing messages, I'll let it to your appreciation :)

2023-06-19 15:06 UTC, bdeneux commented on x/logic/predicate/string_test.go
> +				wantError:   fmt.Errorf("read_string/3: stream could not be a variable"),
```suggestion
				wantError:   fmt.Errorf("read_string/3: stream cannot be a variable"),
```

2023-06-19 15:26 UTC, amimart approved these changes
🚀

2023-06-23 11:18 UTC, ccamel approved these changes
Great! Thanks :+1:

2023-06-23 12:36 UTC, merged