🧠 Logic: `open/4` predicate
okp4/okp4d pull request #393
Opened 2023-06-20 10:04 UTC by bdeneux

Implement our own `open/4` predicate, allowing usage of the virtual file system to open wasm uri which was not used in the ichiban implementation. 
See #379 for more details.

2023-06-23 16:55 UTC, amimart requested changes
Nice piece thanks, I just suggested some corrections on error messages :)

2023-06-23 16:55 UTC, amimart commented on x/logic/predicate/file.go
> +		return engine.Error(fmt.Errorf("open/4: invalid domain for source, should be an atom, give %T", s))
```suggestion
		return engine.Error(fmt.Errorf("open/4: invalid domain for source, should be an atom, got %T", s))
```

2023-06-23 16:55 UTC, amimart commented on x/logic/predicate/file.go
> +		return engine.Error(fmt.Errorf("open/4: invalid domain for open mode, should be an atom, give %T", m))
```suggestion
		return engine.Error(fmt.Errorf("open/4: invalid domain for open mode, should be an atom, got %T", m))
```

2023-06-23 16:55 UTC, amimart commented on x/logic/predicate/file.go
> +		return engine.Error(fmt.Errorf("open/4: stream can only be a variable, give %T", env.Resolve(stream)))
```suggestion
		return engine.Error(fmt.Errorf("open/4: stream can only be a variable, got %T", env.Resolve(stream)))
```

2023-06-23 16:55 UTC, amimart commented on x/logic/predicate/file.go
> +		return engine.Error(fmt.Errorf("open/4: failed open stream: %w", err))
```suggestion
		return engine.Error(fmt.Errorf("open/4: couldn't open stream: %w", err))
```

2023-06-24 15:35 UTC, ccamel approved these changes
:+1:

2023-06-24 16:02 UTC, amimart approved these changes

2023-06-24 16:56 UTC, merged